name: GitHub Actions

on:
  workflow_dispatch:
    inputs:
      hugo_version:
        description: 'What version of Hugo to use'
        required: false
        default: 'v0.136.5'
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set hugo_version output
        id: hugo_version
        run: |
          USER_INPUT=${{ github.event.inputs.hugo_version }}
          echo "value=${USER_INPUT:-"v0.136.5"}" >> "$GITHUB_OUTPUT"

      - name: Check out main
        uses: actions/checkout@main

      - name: Deploy site
        uses: nanodocumet/testing-github-actions@main
        env:
          HUGO_VERSION: ${{ steps.hugo_version.outputs.value }}

